name: reidle
description: Reidle
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_analytics: ^9.1.9
  google_fonts: ^3.0.1
  provider: ^6.0.3
  sendgrid_mailer: ^0.1.3
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

dev_dependencies:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
flutter:
  uses-material-design: true
  assets:
    - assets/words.csv
    - assets/answers.csv
